# GitHub release for GCP versioning
name: release

# The release workflow is triggered by each push with new tag
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Creat a release and upload assets.
      # Note that the release automatically contains source code, the upload assets can be a description file of this version, e.g. change.txt
      - name: Create Release
        run: |
          gh release create ${{ github.ref }} ./*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

### Test Usage ###
# First finish git commit
# $ git tag [tagname] -m '[comment]'
# e.g. $ git tag v1.0.0 -m 'test for versioning'
# git push origin v1.0.0
